### ISSUE TITLE
Error Loading Spoiler Log | Tools > Import Spoiler Log

### ISSUE THREAD

**Issue by LJNeveral** [Thedrummonger/MMR-Tracker-V3#2]
************** Exception Text **************
System.Exception: No Valid Locations Found
{
  "Key": "Odolwa Heart Container",
  "Value": {
    "Locations": [],
    "Items": [
      "Piece of Heart"
    ],
    "Result": {}
  }
}

[Exception.txt](https://github.com/user-attachments/files/15791156/Exception.txt)
[MMR-1.15.2.1-2024-06-11T14-30-29.3853544Z_SpoilerLog.txt](https://github.com/user-attachments/files/15791167/MMR-1.15.2.1-2024-06-11T14-30-29.3853544Z_SpoilerLog.txt)

**Comment by Thedrummonger** [comment]
Are you building the tracker from source by chance? The error in the attached text file is referencing code that doesn't exist in the [latest release](https://github.com/Thedrummonger/MMR-Tracker-V3/tags). If so that would explain this issue as currently the Dev build only works with MMR 1.16 Beta. Support for MMR 1.16 isn't even really finished in the Dev build and probably won't be until MMR 1.16 is out of Beta. Once it is I'll make an official release [here](https://github.com/Thedrummonger/MMR-Tracker-V3/releases).

Luckily however, since you're using MMR 1.15 (based on your spoiler log) you should be able to use the [latest official release](https://github.com/Thedrummonger/MMR-Tracker-V3/tags) for this seed. I actually went ahead and loaded your spoiler log into the linked version of the tracker and confirmed everything imported correctly and the seed showed as completable.

I should also note that when the next version of the tracker comes out, it probably won't support versions of the randomizer earlier that 1.16 since so much has changed and it's not really feasible for me to support multiple version. The earlier version of the tracker should still work fine for 1.15 and below though.

**Comment by LJNeveral** [comment]
Apologies for the delay. Yes i was using the source code. Thank you for your reply. The latest official release did work for me.
