### ISSUE TITLE
[Feature] Netplay support for Majora's Mask

### ISSUE THREAD

**Issue by Kosyne** [Thedrummonger/MMR-Tracker-V3#3]
I've noticed some foundation for netplay support for some games in the tracker, it would be awesome if MM would be supported (particularly for stuff like co-operative play).

**Comment by Thedrummonger** [comment]
If you want to try it out, it _should_ work well enough to use. I did a quick test and updated some broken code, and it seems to at least function with MMR when playing Co-op. Since multi-world isn't available with the standalone randomizer, that obviously won't work.

Unfortunately for now you'll need to build the latest development versions of both the Windows Tracker and Server Client from source. The process should be fairly straightforward using Visual Studio 2022, but you need to use the 2022 Preview version because the tracker is built on DotNet 8. Feel free to ask if you have any setup questions.

Regarding a full release, the tracker is currently on hiatus, at least for Majora's Mask. I don't really play the standalone Majora's Mask randomizer anymore, so I don't really have the drive to continue support for it. That may change in the future, or I might rebuild the tracker to support OOTMM or the Archipelago implementation of Majora's Mask. The latter option would be ideal since I already have a foundation for auto-tracking with Archipelago. But in the end who knows.

**Comment by Kosyne** [comment]
Yeah archipelago would be sweet! Just built it and so far it seems to work, really appreciate it!
